/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snv_app;

import MesClasses.Cnx;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author xor
 */
public class Destockage extends javax.swing.JFrame {

    Connection cn=null;
    ResultSet rs=null;
    ResultSet rs2=null;
    PreparedStatement pst=null;
    PreparedStatement pst2=null;
    PreparedStatement pst3=null;
    
    public Destockage() {
        initComponents();
        cache_qte.setVisible(false);
        cn=Cnx.connect();
         
        
               
                
         String calc_qte = "select qte from produit_entree where id=1";
         
         try {
             
             
             
              pst2=cn.prepareStatement(calc_qte);
               rs2 = pst2.executeQuery();
               
               while (rs2.next()) {
                   cache_qte.setText(rs2.getString(1));
               }
             
         }catch (SQLException exp) {
            Logger.getLogger(Interface_stocke.class.getName()).log(Level.SEVERE, null, exp);
        }
         
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prod_selected = new javax.swing.JTextField();
        id_selected = new javax.swing.JTextField();
        Date_sortie = new com.toedter.calendar.JDateChooser();
        qte_sortie = new javax.swing.JTextField();
        btn_des = new javax.swing.JButton();
        reset_sortie = new javax.swing.JButton();
        cache_qte = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Produit Sélectionné :");

        jLabel2.setText("Reference de produit : ");

        jLabel3.setText("Date de sortie");

        jLabel4.setText("Quantité");

        prod_selected.setEditable(false);

        id_selected.setEditable(false);

        Date_sortie.setDateFormatString("dd-MM-yyyy");

        btn_des.setText("Destocker");
        btn_des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desActionPerformed(evt);
            }
        });

        reset_sortie.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(prod_selected, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(reset_sortie)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Date_sortie, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_des)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(id_selected)
                                .addGap(79, 79, 79))
                            .addComponent(qte_sortie, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cache_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(prod_selected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(id_selected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3))
                    .addComponent(Date_sortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(qte_sortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_des)
                    .addComponent(reset_sortie))
                .addGap(18, 18, 18)
                .addComponent(cache_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desActionPerformed
       
        
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        String produit  = prod_selected.getText();
        int reference   = Integer.parseInt(id_selected.getText());
        String Date     = sdf.format(Date_sortie.getDate());
        int    qte   = Integer.parseInt(qte_sortie.getText()) ;
        int GetQnt   = Integer.parseInt(cache_qte.getText());
       
       
               
               
                String sql = "insert into produit_sortie values ("+reference+",'"+produit+"','"+qte+"','"+Date+"')";
                String sqlupd = "update produit_entree set qte=qte-"+qte+" where Nom_prod='"+produit+"' ";
                
            try {
                
               
                
                 pst=cn.prepareStatement(sql);
                 pst3=cn.prepareStatement(sqlupd);
                 
                 
                 if (qte_sortie.getText().equals("") ) {
                        JOptionPane.showMessageDialog(null,"choiser une quantité svp","Attention",JOptionPane.ERROR_MESSAGE);
                       qte_sortie.requestFocus();
                 }
                 
                 else if (GetQnt < qte) {
                     
                     JOptionPane.showMessageDialog(null,"La quantité que vous avez entre ('"+qte+"') plus grande que la quantité en stock ('"+GetQnt+"')","Opération impossible",JOptionPane.ERROR_MESSAGE);
                       qte_sortie.requestFocus();
                     
                 }else {
                 
            
            pst.executeUpdate();  
             pst3.executeUpdate(sqlupd);
             JOptionPane.showMessageDialog(null,"Opeation termineé");
             
                        }
                 
                 
        
    } catch (SQLException ex) {
            Logger.getLogger(Interface_stocke.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_desActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Destockage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Destockage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Destockage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Destockage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Destockage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_sortie;
    private javax.swing.JButton btn_des;
    private javax.swing.JTextField cache_qte;
    public javax.swing.JTextField id_selected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField prod_selected;
    private javax.swing.JTextField qte_sortie;
    private javax.swing.JButton reset_sortie;
    // End of variables declaration//GEN-END:variables
}
